### PR TITLE
Add "raw" consecutive numbering

### PR DESCRIPTION
**Pull request by prihoda**
I need an option to export the PDB without insertion codes - using a "raw" consecutive numbering. I believe this simple PR should do the trick.

### CODE REVIEW

**Comment by prihoda** [comment]
One more idea. How about adding the numbering in a new REMARK line on top of the PDB? I have to say I actually had no idea the PDB was numbered until it bit me :) Some software is still unable to read insertion codes and people from outside the antibody modeling field expect raw consecutive numbering.

**Comment by jadolfbr** [comment]
Aho numbering scheme does not have insertion codes if you wanted to use that.

**Comment by brennanaba** [comment]
I agree that this would be a helpful feature but as you have it now sequences with "raw" numbering would not be passed through the sequence checks. This could lead to users inputting untruncated sequences which could cause the model to fail.

**Comment by prihoda** [comment]
Awesome, thanks for your adjustments!

**Pull request merged**
